### ISSUE TITLE
Handle cookie situation

### ISSUE THREAD

**Issue by Sara-tfq** [kha333n/youtube-scraper#1]
Hey , I don't know if you'll be able to see this , but when the browser is launched the cookie thing pops up , which doesn't let the video play.

**Comment by kha333n** [comment]
I didn't though that any one will use that.

But its glad to know someone did.

It is working fine for me. It can be country issue. There are some countries where sites show popup about cookies or policies etc. 

What is your country in which you are using script.

Also I am using it on fresh system, no extensions installed on browser or any setting changed. There can be some issue with browser.

Send me screenshot of problem and t
Country in which running script. I'll check this.

**Comment by kha333n** [comment]
Also it not robust script. Properly tested. 

I just made for me and make public for others to see as a starting point. 

If you know programming you can adjust according to your needs.

**Comment by Sara-tfq** [comment]
Allright , I'll give you the info , is there any way I can contact  you on discord , it is way discreet.

You can add me  : .astralog

**Comment by kha333n** [comment]
Done @Sara-tfq
